### ISSUE TITLE
hosts.original is not being honored

### ISSUE THREAD

**Issue by eksperimental** [stablestud/adsorber#18]
```
# To make any changes to this file please edit /etc/hosts.original
# and run 'adsorber update' to apply your changes.
# Or else your changes will be overwritten by Adsorber once a week.
```

I edit hosts.original and run "sudo absorber udpate" and I am not seeing the changes reflected in /etc/hosts

**Comment by stablestud** [comment]
Hi @eksperimental,

thanks for reporting that issue.
Due to your issue #14, I changed the behaviour of adsorber to modify `/etc/hosts` inline, instead of replacing it everytime completely, to cooperate with other tools which might also write into that file.

The text you quoted, comes from an older version which has the old behaviour prior #14 
Therefore your should modify `/etc/hosts` directly and not `/etc/hosts.original`.
The `/etc/hosts.original` is only used as backup, if you feel you need to manually restore it.

Did you update according the release notes?
```
Note for updaters:
Due to changes how we handle the hosts file you'll need to remove/disable Adsorber prior upgrading to this version.
This can be done with either running `adsorber disable` or `./remove_files_from_system.sh`
All your config files will be overwritten by `./place_files_onto_system.sh`.
If you want to keep them, take a copy and restore them afterwards.
```

I recommend you run `adsorber disable` and restore `/etc/hosts.original` back as your `/etc/hosts`.
Then you can install Adsorber again with `adsorber install`

Best regards
Vladislav

**Comment by eksperimental** [comment]
Thank you for your answer. I got a bit lost after those changes and the time that has passed.
I see that what you explain here is in the update instructions for the last release.


> @eksperimental I recommend you run `adsorber disable` and restore `/etc/hosts.original` back as your `/etc/hosts`.
> Then you can install Adsorber again with `adsorber install`

I think it is you mean `adsorber setup`


So, can I safely remove `hosts.previous` and `hosts.original` ?

**Comment by stablestud** [comment]
Yes you're right, I meant `adsorber setup` 
You can safely remove `hosts.previous` without problems,
I would remove `hosts.original` only after it has been restored as `/etc/hosts`

**Comment by eksperimental** [comment]
> Yes you're right, I meant `adsorber setup`
> You can safely remove `hosts.previous` without problems,
> I would remove `hosts.original` only after it has been restored as `/etc/hosts`, making them both identical.

Thank you very much Vladislav.
Awesome piece of software
